In [23]:
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/mohitgupta-omg/Kaggle-SMS-Spam-Collection-Dataset-/master/spam.csv',encoding='ISO-8859-1',usecols=['v1','v2'])

In [24]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [25]:
import nltk
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize as st
from nltk.stem import WordNetLemmatizer as wordnet
import re

In [26]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [27]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [28]:
corpus=[]
wordnet=wordnet()
length = len(df['v2'])
for i in range(length):
  rev=re.sub('[^a-zA-Z]','',df['v2'][i]) #rem anything that isnt a character ie remove nos etc get only teh alphaets
  rev=rev.lower()
  rev=rev.split()
  rev =[wordnet.lemmatize(word) for word in rev if word not in stopwords.words('english')] #if stopwords will lematize other wise ignore
  rev = ' '.join(rev)
  corpus.append(rev)

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500) #
x=cv.fit_transform(corpus).toarray()
y=df['v1']
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [31]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)


In [39]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train,y_train)



MultinomialNB()

In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print("Accuracy",model.score(x_test, y_test))
confusion_matrix(y_test, model.predict(x_test))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy 0.8780269058295964
Confusion matrix:
 [[976   0]
 [136   3]]


In [50]:
y_pred=model.predict(x_test)


In [41]:
model.score(x_test,y_test)

0.8780269058295964

In [52]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[976,   0],
       [136,   3]])